name: Manga Batch Downloader

on:
  # هذا الجزء هو المسؤول عن إظهار الزر في تبويب Actions
  workflow_dispatch:
    inputs:
      manga_url:
        description: 'رابط فصل البداية'
        required: true
        default: 'https://manga-starz.net/manga/doomsday-for-all-me-virus-monarch/1'
      start_ch:
        description: 'من فصل رقم'
        required: true
        default: '1'
      end_ch:
        description: 'إلى فصل رقم'
        required: true
        default: '10'

jobs:
  build:
    runs-on: ubuntu-latest # تحويله إلى أوبونتو أسرع وأرخص في الدقائق
    
    steps:
    - name: Checkout Master Branch
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seleniumbase pillow requests tqdm
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install SeleniumBase Drivers
      run: |
        seleniumbase install chromedriver
        seleniumbase install uc_driver

    - name: Run Downloader Script
      # استخدام القيم التي تدخلها عند التشغيل اليدوي
      run: python downloader.py "${{ github.event.inputs.manga_url }}" "${{ github.event.inputs.start_ch }}" "${{ github.event.inputs.end_ch }}"

    - name: Upload Zip Bundles
      uses: actions/upload-artifact@v4
      with:
        name: manga-zip-bundles
        path: ./downloads/*.zip
        retention-days: 2
