name: Manga Ultimate Downloader

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      manga_url:
        description: 'رابط فصل البداية'
        required: true
        default: 'https://manga-starz.net/manga/doomsday-for-all-me-virus-monarch/1'
      start_ch:
        description: 'من فصل رقم'
        required: true
        default: '1'
      end_ch:
        description: 'إلى فصل رقم'
        required: true
        default: '10'

jobs:
  download_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install SeleniumBase and Tools
        run: |
          pip install seleniumbase pillow requests
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          seleniumbase install chromedriver
          seleniumbase install uc_driver

      - name: Run Downloader
        # سيستخدم المدخلات اليدوية، وإذا اشتغل تلقائياً (Push) سيستخدم القيم الافتراضية
        run: |
          python downloader.py "${{ github.event.inputs.manga_url || 'https://manga-starz.net/manga/doomsday-for-all-me-virus-monarch/1' }}" "${{ github.event.inputs.start_ch || '1' }}" "${{ github.event.inputs.end_ch || '5' }}"

      - name: Upload Bundles
        uses: actions/upload-artifact@v4
        with:
          name: manga-zip-bundles
          path: ./downloads/*.zip
          retention-days: 2
